[env:esp32s3_devkit]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

# --- Board Build Flags (Matches Arduino IDE Settings) ---
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_flags = 
	-D BOARD_HAS_PSRAM
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-I include

# --- Library Dependencies ---
# Using LVGL 8 and a stable GFX library version
lib_deps = 
	lvgl/lvgl@~8.3.11
	moononournation/GFX Library for Arduino @ 1.4.2
	adafruit/Adafruit FT6206 Library
	adafruit/Adafruit BusIO
	robtillaart/TCA9554
	https://github.com/aselectroworks/Arduino-FT6336U.git
    adafruit/Adafruit GFX Library
    adafruit/Adafruit BusIO
	adafruit/MAX6675 library
	br3ttb/PID@^1.2.1
    tzapu/WiFiManager@^2.0.17
	https://github.com/br3ttb/Arduino-PID-AutoTune-Library